### PR TITLE
"Fixed" dynamic logo asset Vite handling in JavaScript

### PR DESCRIPTION
**Pull request by serious-angel**
When you build the project, the images get versioned into `:/dist/assets` directory. This is the default behavior. You may notice that in the transpiled entrypoint HTML file (i.e. `:/dist/index.html`). The default entrypoint refers to valid locations since Vite can determine them and rewrite to expected in the app's build state. With the custom JavaScript like `img.src = '';`, you refer to destinations Vite does not affect at this moment.

In order to let Vite transpile those locations, too, there are options to let it know how to process it.

[This](<https://github.com/yusraparacha/Portfolio/pull/1/commits/d80f6ce36abca3822ce617d7aec95f7bcf6bb3e4#diff-6184d978e70f20434e1a4ffeb49e56100ca0a67ff62f635f82a17e0a9f23ee35R3>) is just the most general option to [handle](<https://vitejs.dev/guide/assets#importing-asset-as-url>) static asset files with Vite. It allows Vite to transpile the script rewriting the destination to the resolved resource path in required environment.

`node_modules` and build files should not be versioned in the most cases.

The are significantly more changes to do in your project I believe, including locations of the images, styles, and well non-entrypoint script files (e.g. in `:/src` respectfully).

### CODE REVIEW

**Comment by yusraparacha** [comment]
great thanks! I'll try to understand what the changes are and then pull
them up!

**Comment by serious-angel** [comment]
> great thanks! I'll try to understand what the changes are and then pull them up!

I was in a hurry and committed the most relevant changes with some refactoring like formatting. Thos should be in separate commits. The actual changes without refactor are just:

https://github.com/yusraparacha/Portfolio/blob/d80f6ce36abca3822ce617d7aec95f7bcf6bb3e4/blender.js#L3-L4

https://github.com/yusraparacha/Portfolio/blob/d80f6ce36abca3822ce617d7aec95f7bcf6bb3e4/blender.js#L128

https://github.com/yusraparacha/Portfolio/blob/d80f6ce36abca3822ce617d7aec95f7bcf6bb3e4/blender.js#L154

**Comment by serious-angel** [comment]
Additionally, please consider cleaning (e.g. [`git gc`](<https://git-scm.com/docs/git-gc>)) or re-creating the repository in more organized state since it's a personal one.

Currently, the repository's size is more than 350 MB! The reason is `node_modules` with some other development files like `:/three.js-dev` added to the repository in commit: <https://github.com/yusraparacha/Portfolio/commit/0e59dd785f0337537d7e95c74f9be7708594e17a>.

The actual project size (with assets) is ~`5.8MB`.

Related: [How can I remove/delete a large file from the commit history in the Git repository?](<https://stackoverflow.com/questions/2100907/how-can-i-remove-delete-a-large-file-from-the-commit-history-in-the-git-reposito>)

**Comment by yusraparacha** [comment]
Np, thank you for your time! I found another way too, getting the img src to work thru DOM.
If you get free, could you check out my portfolio and let me know any critique, currently I have not applied media queries so it'll be responsive on mobile screen only.
My domain is techbyyp.com.
________________________________

**Comment by serious-angel** [comment]
> If you get free, could you check out my portfolio and let me know any critique...

Apologies, but this is a more personal task that requires a more specific approach since this is your own portfolio of a developer who presents their worldview, skills, and experience, and as a developer, you should know the best about your own portfolio I believe. Please don't hurry, take [time](<https://vitejs.dev/guide>) into your own presentation, including its technical details like optimization and [responsiveness](<https://www.browserstack.com/responsive>) on required devices.

**Comment by yusraparacha** [comment]
Aight, thanks
________________________________

**Pull request merged**
